.eslintrc, .storybook/main.js, .storybook/preview.js, .vscode/settings.json, README.md, package.json, src/components/PlsPlusAddress/PlsPlusAddress.form.js, src/components/PlsPlusAddress/PlsPlusAddress.js, src/components/PlsPlusAddress/PlsPlusAddress.stories.mdx, src/components/PlsPlusAddress/editForm/PlsPlusAddress.edit.data.js, src/components/PlsPlusAddress/editForm/PlsPlusAddress.edit.display.js, src/components/PlsPlusAddress/editForm/PlsPlusAddress.edit.provider.js, src/components/PlsPlusAddress/index.js, src/components/index.js, src/stories/Welcome.stories.mdx, src/templates/bootstrap/index.js, src/templates/bootstrap/plsPlusAddress/form.ejs, src/templates/bootstrap/plsPlusAddress/html.ejs, src/templates/bootstrap/plsPlusAddress/index.js, src/templates/index.js, yarn.lock
=> Qol 8091 pls plus address

src/helpers/FormioLoader/index.js
as title, in case of default callback function needed to be disabled or overriden
=> add opt.createFormCallback to initFormioInstance

.storybook/main.js
fix the code snippet issue in storybook build, where line breaks have been removed in sample code
=> Release v1.0.4

.storybook/main.js, src/examples/SimpleWizard/SimpleWizard.code.js, src/examples/SingleSignOn/SingleSignOn.code.js
=> fix story code snippet in build

src/helpers/FormioLoader/FormioLoader.js, src/helpers/FormioLoader/FormioLoader.stories.mdx
in order for any use case to override customiseErrorMessage
=> add hook to FormioLoader

src/helpers/FormioScript/index.gitbridge.js
as title
fix gitbridge option in squiz UAT
=> Qol 8650 fix gitbridge issue in formio script

README.md, package.json
- update readme for the squiz matrix testing approach
- update version in package.json
=> Release v1.0.5

.storybook/preview.js, jest.config.js, package-lock.json, package.json, src/components/BoilerplateButton/BoilerplateButton.stories.mdx, src/components/PlsPlusAddress/PlsPlusAddress.stories.mdx, src/components/Radio/Radio.stories.mdx, src/components/Radio/radio.scss, src/helpers/FormioScript/FormioScript.js, src/helpers/FormioScript/FormioScript.stories.mdx, src/helpers/FormioScript/index.gitbridge.js, src/helpers/FormioScript/index.prod.js, src/index.js, src/sass/formio.form.scss, src/test/setupTest.js
add CSS/sass support to repo
- add base sass folder
- update FormioScript to lazy load formio-qld.min.css
- update jest settings to support sass
- re-organise storybook component structure
- add Radio story as boilerplate to show how to add a custom class
=> Qol 8867 add css support

src/components/PdfSubmitButton/PdfSubmitButton.stories.mdx, src/components/index.dev.js
fix merge conflict on PdfSubmitButton and storybook re-structure
=> fix merge conflict on PdfSubmitButton and storybook re-structure

.storybook/main.js, README.md, src/helpers/FormioScript/FormioScript.stories.mdx, src/stories/How.stories.mdx, src/stories/Welcome.stories.mdx, src/stories/WhyAndWhen.stories.mdx, src/stories/assets/Grab my IP (grabMyIp)-Resource.json, src/stories/assets/Grab my IP example (grabMyIpExample)-Form.json
- update readme
- re-organise storybook doc pages
- add `how to` page
- add `why and when` page
=> update readme and storybook

.storybook/main.js, .storybook/preview-head.html, package-lock.json, package.json, src/examples/DownloadPdf/DownloadPdf.code.js, src/examples/DownloadPdf/DownloadPdf.stories.mdx, src/examples/DownloadPdf/DownloadPdfWizard.code.js, src/examples/SimpleWizard/SimpleWizard.code.js, src/examples/SingleSignOn/SingleSignOn.code.js, src/helpers/FormioLoader/FormioLoader.js, src/test/setupTest.js, src/utils/delegateSelector.js
remove jquery dependency from FormioLoader
=> Remove jquery reference from custom component library

src/components/PlsPlusAddress/sass/plsPlusAddress.swe.scss, src/components/Radio/sass/radio.ds.scss, src/components/Radio/sass/radio.swe.scss, src/templates/bootstrap/plsPlusAddress/form.ejs
- add style to plsPlusAddress
- update radio style
=> Qol 8950 update plu plus address default label and style

src/stories/BestPratices.stories.mdx
add the best practices page in storybook documentation to record any supported issues which is worth taking notes
=> add best practices stories

src/config/createForm.controller.js
fix GA tracking code tht inherited from legacy formio-loader.js in squiz matrix asset (144217)
=> update GA snippet

package.json
same PR as https://github.com/qld-gov-au/formio/pull/76
but merge to main (release v1.1.x, with formio v7.4)
=> add support to iOS 12

src/config/createForm.options.js, src/helpers/FormioLoader/FormioLoader.js, src/helpers/FormioLoader/FormioLoader.stories.mdx
same as https://github.com/qld-gov-au/formio/pull/83 but cherrypick to release 1.1.x instead 1.0.x
=> Qol 8947 customise formio error and success message

CHANGELOG.md, src/examples/SingleSignOn/SingleSignOn.stories.mdx, src/examples/SingleSignOn/index.js, src/examples/SingleSignOn/stories/SSOUnauth.code.js, src/examples/SingleSignOn/stories/SSOUnauth.js, src/examples/SingleSignOn/stories/SingleSignOn.code.js, src/examples/SingleSignOn/stories/SingleSignOn.js, src/stories/How.stories.mdx
- explore any other alternative for the logout action
- only popup approavh is available due to security settings in the logout page header
- improve the popup logout approach, by checking logout action is completly finished
- improve loading indicator
- add story for direct access to the actual form
more changes to the form in https://api.forms.platforms.qld.gov.au/#/project/612eeb800db6b412a3f37e1f/form/62564e89bbc38d840d92b664/edit
- extract reusable variables as individual data properties
- fix the way to get namespace
- fix the condition to show/hide submit button and message
- add condition to prevent access the form directly (display warning message)
=> Qol 9130 sso demo improvement

src/examples/SingleSignOn/stories/SingleSignOn.js
fix logout redirect doesn't work for github page
=> fix sso logout redirectUri

src/components/Button/sass/button.swe.scss, src/sass/formio.form.swe.scss, src/templates/bootstrap/boilerplateButton/form.ejs
update style for loading spinner in formio submit button
in Squiz Matrix, change will only take effect in V2 Formio component
=> update button spinner style

src/config/createForm.controller.js, src/utils/pushDataLayer.js
add extra ga tracking events to submission
=> Dc 33010 add ga tracking events

lib/versions.txt, src/helpers/FormioLoader/FormioLoader.js
- fix an issue in FormioLoader that would affect nested form implementation
- update versions.txt
=> fix FormioLoader nested form implementation

src/helpers/FormioLoader/FormioLoader.js
This should resolve issues with resources not finding project and still allow revision's on forms.
=> QOLSVC-11360 Fix #943 Swap from /v/ to ?formRevision
